[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "xxxxxx"

[auth.auth0]
client_id = "2hsTQn8TijBbZLhpm2NJRFowUsHelPoI"
client_secret = "ssKLN0Wrv25Nprb5RCyEGS2b6p-DiRr61FHJa5_cap2P2ZvDcXcPTsyHmeArplbY"
server_metadata_url = "https://dev-ieov28ddffnkz1no.us.auth0.com/.well-known/openid-configuration"  # fmt: skip
client_kwargs = { "prompt" = "login" }