# secrets.toml

[auth]
#redirect_uri = "http://localhost:8501/oauth2callback"

redirect_uri = "https://blaktower-analytics.streamlit.app/oauth2callback"
cookie_secret = "xxxxxx"

[auth.auth0]
client_id = "2hsTQn8TijBbZLhpm2NJRFowUsHelPoI"
client_secret = "ssKLN0Wrv25Nprb5RCyEGS2b6p-DiRr61FHJa5_cap2P2ZvDcXcPTsyHmeArplbY"
server_metadata_url = "https://dev-ieov28ddffnkz1no.us.auth0.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }

# Agrega tus variables privadas así:
[TWILIO]
ACCOUNT_SID = "AC72a36f351bca275c87bb4e256435f54f"
AUTH_TOKEN = "183757131de722743678dd109a65a3f3"
FROM = "arcosecantex"

[OPENAI]
CHATGPTAPIKEY = "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"
CHATGPTAPIKEYMARDUK = "sk-proj-1mI6F2r6DRGt_ZwZignLBVPqYDjygSnlFuAMoKjF6TZKm2wmKJPhoguvl_Hiu6sagSOkuM-C1VT3BlbkFJb2E09dRpgp8AhctEkoKDkhhdWc1up3R6QhsgVlGYBcu2dWd4owXCwPunsUwoPy3nPnhcFhAA"

[WHATSAPP]
SID = "AC72a36f351bca275c87bb4e256435f54f"
AUTHTOKEN = "183757131de722743678dd109a65a3f3"
TOKEN = "EAAItlliVsEwBOyOZCtNxJfhJcuNSickQfo4kOUkBDVJeAtenAJX13rfMteaptcU4Ed9hgAjXHJhIxRtpP0RgNeDTOaNhCuPZApgZB8GPslCX686pFWAf4OgFBwcZBwCoDzSZBQxxquXAF7FTHXLiXIms1v4G651dJShCtX4N4xYKcQoozV5hGCVrxoX3AvutquAZDZD"
PHONE_ID = "530396030160376"
VERIFY_TOKEN = "eaqndlv"

[DB]
DATABASE = "arcobits"
SANDBOX_DATABASE = "arcobits_sandbox"
URIMONGODB = "mongodb+srv://fox1:modelotx30@arcobitscluster0.w6meunj.mongodb.net/?retryWrites=true&w=majority&appName=ArcobitsCluster0"

[SMTP]
username = "er"
password = "er"